on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: git stuff
        run: |
          git config --global --add safe.directory /github/workspace
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v1
        with:
          origin: 'https://git.arthurmelton.com/greynoise-cli'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
